# Production deployment configuration
version: '3.8'

services:
  interior-ai-studio:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REPLICATE_API_TOKEN=${REPLICATE_API_TOKEN}
      - INTERIOR_AI_API_KEY=${INTERIOR_AI_API_KEY:-demo-changeme-not-secure}
      - NEO4J_URI=${NEO4J_URI:-neo4j://neo4j:7687}
    depends_on:
      - neo4j
    restart: unless-stopped

  neo4j:
    image: neo4j:5.13
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-secure-neo4j-password-change-me}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

volumes:
  neo4j_data: